from __future__ import annotations

from typing import Protocol


class MoySkladClient(Protocol):
    async def find_product_by_article(self, article: str) -> dict | None: ...
    async def find_product_by_supplier_code(self, code: str) -> dict | None: ...
    async def search_products(self, query: str) -> list[dict]: ...
    async def create_product(self, payload: dict) -> dict: ...
    async def update_product(self, ms_id: str, payload: dict) -> dict: ...
    async def upload_image(self, ms_id: str, image_path: str) -> dict: ...
    async def get_or_create_folder(self, name: str) -> dict: ...
    async def get_uom(self, name: str) -> dict | None: ...
    async def find_counterparty(self, name: str) -> dict | None: ...
    async def set_published_flag(self, ms_id: str, value: bool) -> dict: ...
