from __future__ import annotations

from decimal import Decimal
from typing import Protocol


class SiteClient(Protocol):
    async def find_product_by_ms_code(self, ms_code: str) -> dict | None: ...
    async def create_or_update_product(self, payload: dict) -> dict: ...
    async def set_properties(self, site_id: str, properties: dict) -> None: ...
    async def upload_images(
        self,
        site_id: str,
        extra: list[str],
        announce: list[str],
        detail: list[str],
    ) -> None: ...
    async def set_catalog_price(self, site_id: str, price: Decimal) -> None: ...
    async def set_unit_coefficient(self, site_id: str, coef: Decimal) -> None: ...
    async def disable_quantity_accounting(self, site_id: str) -> None: ...
    async def set_card_type(self, site_id: str, value: str = "Ламинат") -> None: ...
    async def set_supplier_name(self, site_id: str, supplier: str) -> None: ...
    async def publish(self, site_id: str) -> None: ...
